import type { Rng } from '@/types/rng.ts';
import type { AudioIndex, CueDefinition, CueId } from './catalog.ts';

const INDEX_URL = '/audio/index.json';

/**
 * Loads and serves the procedural sound bank.
 *
 * Buffers are decoded once into the module's own `AudioContext`. This
 * deliberately bypasses `ResourceManager.getAudio`: the manifest in
 * `public/assets/` is owned by the offline asset pipeline and describes
 * third-party downloads, whereas this bank is generated by
 * `tools/audio/generate.mjs` and has its own index. Keeping them separate
 * means neither pipeline can break the other.
 *
 * Nothing here throws. A missing or malformed bank leaves the game silent,
 * which is always preferable to a boot failure.
 */
export class SoundBank {
  #ctx: AudioContext;
  #rng: Rng;
  #index: AudioIndex | null = null;
  #buffers = new Map<string, AudioBuffer[]>();
  /** Remaining variant indices for the current shuffle of each cue. */
  #bags = new Map<string, number[]>();
  #lastPicked = new Map<string, number>();
  #failures = 0;

  loaded = false;

  constructor(ctx: AudioContext, rng: Rng) {
    this.#ctx = ctx;
    this.#rng = rng;
  }

  /**
   * Fetches the index and, unless `indexOnly`, decodes every variant.
   *
   * The capture harness passes `indexOnly`: it never produces a user gesture,
   * so the context stays suspended and nothing can be heard. Decoding two
   * megabytes of WAV there would only add load time and frame-time jitter to
   * a screenshot run, while still exercising the fetch and parse path.
   */
  async load(indexOnly = false): Promise<void> {
    try {
      const res = await fetch(INDEX_URL);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      this.#index = (await res.json()) as AudioIndex;
    } catch (err) {
      console.warn('[audio] sound bank index unavailable; running silent', err);
      return;
    }
    if (indexOnly) {
      this.loaded = true;
      return;
    }

    const jobs: Array<{ cue: string; url: string; slot: number }> = [];
    for (const [cue, def] of Object.entries(this.#index.cues)) {
      this.#buffers.set(cue, new Array<AudioBuffer>(def.variants.length));
      def.variants.forEach((v, slot) => jobs.push({ cue, url: v.url, slot }));
    }

    // Bounded concurrency: enough to keep the connection busy without
    // queueing dozens of simultaneous decodes on the audio thread while the
    // renderer is still uploading textures.
    const CONCURRENCY = 6;
    let cursor = 0;
    const worker = async (): Promise<void> => {
      while (cursor < jobs.length) {
        const job = jobs[cursor++];
        if (!job) break;
        try {
          const res = await fetch(job.url);
          const bytes = await res.arrayBuffer();
          const buffer = await this.#ctx.decodeAudioData(bytes);
          const slots = this.#buffers.get(job.cue);
          if (slots) slots[job.slot] = buffer;
        } catch {
          this.#failures++;
        }
      }
    };
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));

    // Drop any variant that failed so playback never sees a hole.
    for (const [cue, slots] of this.#buffers) {
      const present = slots.filter(Boolean);
      if (present.length === 0) this.#buffers.delete(cue);
      else this.#buffers.set(cue, present);
    }
    if (this.#failures > 0) {
      console.warn(`[audio] ${this.#failures} sound variant(s) failed to decode`);
    }
    this.loaded = true;
  }

  has(cue: CueId): boolean {
    return (this.#buffers.get(cue)?.length ?? 0) > 0;
  }

  definitionOf(cue: CueId): CueDefinition | null {
    return this.#index?.cues[cue] ?? null;
  }

  /** Every cue with at least one decoded variant. */
  cueIds(): string[] {
    return Array.from(this.#buffers.keys()).sort();
  }

  gainOf(cue: CueId): number {
    return this.#index?.cues[cue]?.gain ?? 1;
  }

  /** Returns a specific variant. Used for impulse responses and loops. */
  first(cue: CueId): AudioBuffer | null {
    return this.#buffers.get(cue)?.[0] ?? null;
  }

  /**
   * Round-robin variant selection from a shuffled bag.
   *
   * A plain cycle is audible as a pattern under sustained fire, and pure
   * random repeats a variant back-to-back about a quarter of the time. A bag
   * that reshuffles when empty, with the constraint that a refill never
   * starts with the variant that just played, gives even coverage and no
   * immediate repeats.
   */
  pick(cue: CueId): AudioBuffer | null {
    const variants = this.#buffers.get(cue);
    if (!variants || variants.length === 0) return null;
    if (variants.length === 1) return variants[0];

    let bag = this.#bags.get(cue);
    if (!bag || bag.length === 0) {
      bag = variants.map((_, i) => i);
      for (let i = bag.length - 1; i > 0; i--) {
        const j = this.#rng.int(0, i);
        [bag[i], bag[j]] = [bag[j], bag[i]];
      }
      const last = this.#lastPicked.get(cue);
      if (last !== undefined && bag[bag.length - 1] === last && bag.length > 1) {
        [bag[bag.length - 1], bag[0]] = [bag[0], bag[bag.length - 1]];
      }
      this.#bags.set(cue, bag);
    }

    const index = bag.pop() as number;
    this.#lastPicked.set(cue, index);
    return variants[index];
  }

  /** Diagnostics for the runtime verification harness. */
  stats(): { cues: number; buffers: number; failures: number; bytes: number } {
    let buffers = 0;
    let bytes = 0;
    for (const slots of this.#buffers.values()) {
      for (const b of slots) {
        // Slots stay sparse if loading was interrupted by a teardown.
        if (!b) continue;
        buffers++;
        bytes += b.length * b.numberOfChannels * 4;
      }
    }
    return { cues: this.#buffers.size, buffers, failures: this.#failures, bytes };
  }
}
